### ISSUE TITLE
Padding causes studders if the intial state is closed in 3.0.1

### ISSUE THREAD

**Issue by mrkmiller** [zgrybus/slideToggle#16]
Padding on the element being toggled now causes problems in 3.0.1 if the initial state is closed.

**How to reproduce:**
1. Edit the demo "show" event and change the speed to 2000ms so it can be better seen.
2. Edit the `.section .toggle-list .toggled-list-element` and add a top and bottom padding of 100px.

Instead of slowly sliding all content open, it will immediately display all content based on the height of the combined padding before sliding open the rest.
![image](https://user-images.githubusercontent.com/28543038/127034756-51b86e89-8994-4cae-930f-991f07e62518.png)

**Comment by zgrybus** [comment]
@mrkmiller Fixed in [3.2.1](https://github.com/zgrybus/slideToggle/compare/v3.1.0...v3.2.1)

**Comment by mrkmiller** [comment]
Thanks for the work... but unfortunately this still appears to be a problem in 3.2.2. I created a codepen to demo content using no padding vs having padding.
https://codepen.io/segovia94/pen/mdwybgK

**Comment by mrkmiller** [comment]
Actually, this appears to only be an issue within Firefox now. Chrome is working fine.

**Comment by zgrybus** [comment]
@mrkmiller 
Released in https://github.com/zgrybus/slideToggle/releases/tag/v3.3.1

**Comment by zgrybus** [comment]
Hi @mrkmiller.
I'm really sorry for the long wait for an answer..

I ported this library to the Animation API (https://github.com/zgrybus/slideToggle/releases/tag/v4.0.0). Can you check if this issue still occurs? show and hide should be fixed. My guess is that this switch still has a bug which I will fix in the next version (v4.0.1)
